version: '2'

services:
  invoker:
    build:
        context: invoker/
        dockerfile: Dockerfile
    image: moleculer_invoker.image
    environment:
        - AMQP_URL=amqp://rabbitmq:rabbitmq@rabbit1:5672/
        - JAEGER=http://jaeger:14268/api/traces
    depends_on:
      - rabbit1
      - jaeger

  service1:
    build:
        context: service1/
        dockerfile: Dockerfile
    image: moleculer_service1.image
    environment:
        - AMQP_URL=amqp://rabbitmq:rabbitmq@rabbit1:5672/
        - JAEGER=http://jaeger:14268/api/traces
    depends_on:
      - rabbit1
      - jaeger

  service2:
    build:
        context: service2/
        dockerfile: Dockerfile
    image: moleculer_service2.image
    environment:
        - AMQP_URL=amqp://rabbitmq:rabbitmq@rabbit1:5672/
        - JAEGER=http://jaeger:14268/api/traces
    depends_on:
      - rabbit1
      - jaeger

  rabbit1:
    image: "rabbitmq:3"
    hostname: "rabbit1"
    environment:
      #RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      #RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"


  jaeger:
    image: jaegertracing/all-in-one:1.13.1
    container_name: test-jaeger
    mem_limit: 512m
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411


